version: '3.1'

services:
  account:
    image: "account"
    container_name: account
    ports:
      - "9000:9000"
    volumes:
      - "./data/conf:/data/conf"
    networks:
      - default-net

networks:
  default-net:
    external:
      name: dev_bridge
